### ISSUE TITLE
JSX support?

### ISSUE THREAD

**Issue by buddyp450** [virtkick/node-serve-jspm#2]
In the README it mentioned this supported using the JSX out of the box but I encounter an error as soon as the first JSX is read from my index?

```
SyntaxError: /index.jsx: Unexpected token (8:2)
   6 |
   7 | ReactDOM.render(
>  8 |   <Provider store={store}>
     |   ^
   9 |     <Router />
  10 |   </Provider>,
  11 |   document.getElementById('content')
    at Parser.pp.raise babel@0.0.17/systemjs-babel-node.js:36759:15)
    at Parser.pp.unexpected
    at Parser.pp.parseExprAtom 
    at Parser.pp.parseExprSubscripts 
    at Parser.pp.parseMaybeUnary 
    at Parser.pp.parseExprOps 
    at Parser.pp.parseMaybeConditional 
    at Parser.pp.parseMaybeAssign 
    at Parser.pp.parseExprListItem 
    at Parser.pp.parseCallExpressionArguments 
    at Parser.pp.parseSubscripts 
    at Parser.pp.parseExprSubscripts 
    at Parser.pp.parseMaybeUnary 
    at Parser.pp.parseExprOps 
    at Parser.pp.parseMaybeConditional 
    at Parser.pp.parseMaybeAssign 
```

I'm using http-proxy to proxy the requests for /jspm_packages and /app to my jspm_packages and app folders respectively on an express server running on a different port specifically for the purpose of running the serveJspm module (that's all the express server does). Any tips?

**Comment by Rush** [comment]
Hey, could you share some example that breaks? I'd gladly fix it if I get a small testcase.

**Comment by Rush** [comment]
Have you installed http://jspm.io/0.17-beta-guide/installing-the-jsx-babel-plugin.html ?

**Comment by buddyp450** [comment]
Yes @ 6.8.0, I'll try and get a test case asap

**Comment by Rush** [comment]
I just pushed some JSX tests (both babel+jsx and jsx loader) and it appears to be working just fine. Run `npm test` to try. You can see my testing  configs for hints. I bet you're not setting the right meta configuration. You need to either set jsx babel plugin or use the jsx loader.

**Comment by buddyp450** [comment]
Thank you, closing this issue until I can review the tests and check my config. If I can confirm something is in fact broken I'll re-open.

**Comment by Rush** [comment]
@buddyp450 were you able to make it work? Please post the solution here as others may find it useful.
